apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/mysql/
