apiVersion: apps/v1
kind: Deployment
metadata:
  name: person #Deployment name
  namespace: person
  labels:
    app: person #label to find the respective pods to manage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: person
  template: #template for the replica/pod specification
    metadata:
      labels:
        app: person #label for the corresponding app
    spec:
      containers:
        - name: person #container name
          image: sdam/citizen-spring-rest:0.1 #container image
          ports:
            - containerPort: 30000 #container port
          env: #get environment vars from specific secret
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: password
            - name: DB_HOST
              value: "mysql"
            - name: DB_NAME
              value: "citizens"
            - name: SERVER_PORT
              value: "30000"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "2"
